manifest:
  remotes:
    - name: gwthmpsn
      url-base: https://github.com/gwthmpsn
  projects:
    - name: zmk-drorchen
      remote: gwthmpsn
      revision: trackball-support # luberry
      import: app/west.yml
  self:
    path: config
