manifest:
  remotes:
    - name: drorchen
      url-base: https://github.com/drorchen
  projects:
    - name: zmk
      remote: drorchen
      revision: trackball-support
      import: app/west.yml
  self:
    path: config
