manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Luberry
      url-base: https://github.com/Luberry/
  projects:
    - name: zmk
      remote: Luberry
      revision: pmw3389
      import: app/west.yml
  self:
    path: config
