manifest:
  remotes:
    - name: gwthmpsn
      url-base: https://github.com/gwthmpsn
  projects:
    - name: zmk
      remote: gwthmpsn
      revision: main
      import: app/west.yml
  self:
    path: config
